import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/config/theme-provider";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Providers from "../config/providers";
import "./globals.css";

const roboto = Roboto({
	style: ["italic", "normal"],
	subsets: ["latin", "vietnamese"],
	weight: ["100", "200", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={`antialiased ${roboto.className}`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<Providers>{children}</Providers>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
