import type { PricingPlan, PricingTabKey } from "./pricing.types";

export const pricingData: Record<PricingTabKey, PricingPlan[]> = {
	individuals: [
		{
			id: "personal",
			name: "Personal",
			description:
				"For individuals and small teams looking to manage their tasks.",
			price: "US $0",
			priceSuffix: "Free forever",
			intro: "Manage tasks and personal to-dos:",
			features: [
				"Collaborate with up to 10 teammates",
				"Unlimited tasks",
				"Unlimited projects",
				"Unlimited messages",
				"Unlimited activity log",
				"Unlimited file storage (100MB per file)",
				"Basic search filters",
				"Status updates",
				"iOS and Android mobile apps",
				"Time tracking with integrations",
				"100+ free integrations with your favorite apps",
			],
		},
		{
			id: "starter",
			name: "Starter",
			description:
				"For growing teams that need to track their project's progress.",
			price: "US$10.99",
			priceSuffix: "per month",
			intro: "Everything in Personal, plus:",
			features: [
				"Collaborate with up to 500 teammates",
				"Taskmanly Intelligence",
				"Workflow Builder",
				"Project dashboards",
				"Advanced search",
				"Global custom fields",
				"Forms",
				"250 Automations per month",
				"Start dates and times",
				"Custom project templates",
				"Private teams & projects",
				"Unlimited free guests",
			],
		},
		{
			id: "advanced",
			name: "Advanced",
			description:
				"For companies that need to manage a portfolio of work.",
			price: "US$24.99",
			priceSuffix: "per month",
			intro: "Everything in Starter, plus:",
			features: [
				"Collaborate with up to 500 teammates",
				"Goals",
				"20 Portfolios",
				"Taskmanly Intelligence",
				"Workload",
				"25,000 Automations per month",
				"Forms branching & customization",
				"Approvals",
				"Lock custom fields",
				"Advanced reporting",
				"Time tracking",
				"Scaled security",
			],
		},
	],
	businesses: [
		{
			id: "personal-business",
			name: "Personal",
			description:
				"For individuals and small teams looking to manage their tasks.",
			price: "US $0",
			priceSuffix: "Free forever",
			intro: "Manage tasks and personal to-dos:",
			features: [
				"Collaborate with up to 10 teammates",
				"Unlimited tasks",
				"Unlimited projects",
				"Unlimited messages",
				"Unlimited activity log",
				"Unlimited file storage (100MB per file)",
				"Basic search filters",
				"Status updates",
				"iOS and Android mobile apps",
				"Time tracking with integrations",
				"100+ free integrations with your favorite apps",
			],
		},
		{
			id: "starter-business",
			name: "Starter",
			description:
				"For growing teams that need to track their project's progress.",
			price: "US$10.99",
			priceSuffix: "per month",
			intro: "Everything in Personal, plus:",
			features: [
				"Collaborate with up to 500 teammates",
				"Taskmanly Intelligence",
				"Workflow Builder",
				"Project dashboards",
				"Advanced search",
				"Global custom fields",
				"Forms",
				"250 Automations per month",
				"Start dates and times",
				"Custom project templates",
				"Private teams & projects",
				"Unlimited free guests",
			],
		},
		{
			id: "advanced-business",
			name: "Advanced",
			description:
				"For companies that need to manage a portfolio of work.",
			price: "US$24.99",
			priceSuffix: "per month",
			intro: "Everything in Starter, plus:",
			features: [
				"Collaborate with up to 500 teammates",
				"Goals",
				"20 Portfolios",
				"Taskmanly Intelligence",
				"Workload",
				"25,000 Automations per month",
				"Forms branching & customization",
				"Approvals",
				"Lock custom fields",
				"Advanced reporting",
				"Time tracking",
				"Scaled security",
			],
		},
	],
};
