import type { AdminAuditLog } from "./audit-log-admin.types";

export const adminAuditLogs: AdminAuditLog[] = [
	{
		id: "log_1",
		actorId: "u_1",
		actorName: "Nguyen Anh Nam",
		actorEmail: "nam@example.com",
		action: "WORKSPACE_CREATED",
		targetType: "WORKSPACE",
		targetId: "ws_1",
		targetName: "Acme Inc.",
		severity: "INFO",
		description: "Tạo workspace mới Acme Inc.",
		createdAt: "2026-04-19T08:20:00.000Z",
		ipAddress: "103.21.244.10",
		userAgent: "Chrome / Windows",
		before: null,
		after: {
			name: "Acme Inc.",
			slug: "acme-inc",
			plan: "FREE",
			status: "ACTIVE",
		},
	},
	{
		id: "log_2",
		actorId: "u_2",
		actorName: "Bui Hoang Yen",
		actorEmail: "yen@example.com",
		action: "USER_LOCKED",
		targetType: "USER",
		targetId: "u_12",
		targetName: "Le Thi Huong",
		severity: "CRITICAL",
		description: "Khóa tài khoản do phát hiện đăng nhập bất thường.",
		createdAt: "2026-04-18T15:10:00.000Z",
		ipAddress: "27.72.98.100",
		userAgent: "Edge / Windows",
		before: {
			status: "ACTIVE",
		},
		after: {
			status: "LOCKED",
		},
	},
	{
		id: "log_3",
		actorId: "u_2",
		actorName: "Bui Hoang Yen",
		actorEmail: "yen@example.com",
		action: "USER_UNLOCKED",
		targetType: "USER",
		targetId: "u_12",
		targetName: "Le Thi Huong",
		severity: "WARNING",
		description: "Mở khóa lại tài khoản sau khi xác minh.",
		createdAt: "2026-04-18T17:40:00.000Z",
		ipAddress: "27.72.98.100",
		userAgent: "Edge / Windows",
		before: {
			status: "LOCKED",
		},
		after: {
			status: "ACTIVE",
		},
	},
	{
		id: "log_4",
		actorId: "u_3",
		actorName: "Kai Sou",
		actorEmail: "kai@example.com",
		action: "ROLE_CHANGED",
		targetType: "ROLE",
		targetId: "role_1",
		targetName: "Workspace Admin -> Member",
		severity: "WARNING",
		description:
			"Thay đổi quyền của Tran Minh Khoa trong workspace Nova Team.",
		createdAt: "2026-04-17T13:30:00.000Z",
		ipAddress: "14.161.32.8",
		userAgent: "Chrome / macOS",
		before: {
			workspace: "Nova Team",
			user: "Tran Minh Khoa",
			role: "ADMIN",
		},
		after: {
			workspace: "Nova Team",
			user: "Tran Minh Khoa",
			role: "MEMBER",
		},
	},
	{
		id: "log_5",
		actorId: "u_4",
		actorName: "Olivia Nguyen",
		actorEmail: "olivia@example.com",
		action: "BILLING_CHANGED",
		targetType: "BILLING",
		targetId: "sub_6",
		targetName: "Growth Lab Subscription",
		severity: "INFO",
		description: "Nâng gói Growth Lab từ Pro lên Enterprise.",
		createdAt: "2026-04-17T09:00:00.000Z",
		ipAddress: "113.161.72.55",
		userAgent: "Chrome / Linux",
		before: {
			plan: "PRO",
			amount: 29,
			storageLimitGb: 25,
		},
		after: {
			plan: "ENTERPRISE",
			amount: 99,
			storageLimitGb: 100,
		},
	},
	{
		id: "log_6",
		actorId: "u_5",
		actorName: "Nass",
		actorEmail: "nass@example.com",
		action: "WORKSPACE_LOCKED",
		targetType: "WORKSPACE",
		targetId: "ws_3",
		targetName: "Pixel Studio",
		severity: "CRITICAL",
		description: "Khóa workspace do phát hiện hoạt động nghi vấn.",
		createdAt: "2026-04-16T10:10:00.000Z",
		ipAddress: "115.74.10.200",
		userAgent: "Chrome / Windows",
		before: {
			status: "ACTIVE",
		},
		after: {
			status: "LOCKED",
		},
	},
	{
		id: "log_7",
		actorId: "u_5",
		actorName: "Nass",
		actorEmail: "nass@example.com",
		action: "WORKSPACE_DELETED",
		targetType: "WORKSPACE",
		targetId: "ws_4",
		targetName: "Moon Labs",
		severity: "WARNING",
		description: "Xóa mềm workspace Moon Labs.",
		createdAt: "2026-04-15T11:45:00.000Z",
		ipAddress: "115.74.10.200",
		userAgent: "Chrome / Windows",
		before: {
			status: "ACTIVE",
			deletedAt: null,
		},
		after: {
			status: "DELETED",
			deletedAt: "2026-04-15T11:45:00.000Z",
		},
	},
	{
		id: "log_8",
		actorId: "u_6",
		actorName: "Super Admin Root",
		actorEmail: "root@example.com",
		action: "ADMIN_LOGIN",
		targetType: "AUTH",
		targetId: "session_101",
		targetName: "Admin Portal",
		severity: "INFO",
		description: "Đăng nhập thành công vào khu vực super admin.",
		createdAt: "2026-04-19T07:55:00.000Z",
		ipAddress: "42.112.90.11",
		userAgent: "Chrome / Windows",
		before: null,
		after: {
			result: "SUCCESS",
			location: "Ho Chi Minh City",
		},
	},
];
