import type {
	MonitoringEvent,
	MonitoringService,
	MonitoringSnapshot,
} from "./monitoring-admin.types";

export const monitoringSnapshot: MonitoringSnapshot = {
	apiUptimePercent: 99.91,
	errorRatePercent: 2.8,
	failedJobs: 18,
	failedEmails: 34,
	failedWebhooks: 12,
	openAlerts: 5,
	avgResponseTimeMs: 186,
};

export const adminMonitoringServices: MonitoringService[] = [
	{
		id: "svc_1",
		name: "API Gateway",
		category: "API",
		status: "DEGRADED",
		uptimePercent: 99.82,
		responseTimeMs: 248,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message: "Độ trễ tăng tại cụm ap-southeast-1.",
		region: "ap-southeast-1",
	},
	{
		id: "svc_2",
		name: "Core API",
		category: "API",
		status: "HEALTHY",
		uptimePercent: 99.97,
		responseTimeMs: 132,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message: "Tất cả endpoint chính đang ổn định.",
		region: "global",
	},
	{
		id: "svc_3",
		name: "PostgreSQL Cluster",
		category: "DATABASE",
		status: "HEALTHY",
		uptimePercent: 99.99,
		responseTimeMs: 24,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message: "Replication và query latency trong ngưỡng bình thường.",
		region: "primary-db",
	},
	{
		id: "svc_4",
		name: "Redis Queue",
		category: "QUEUE",
		status: "DEGRADED",
		uptimePercent: 99.41,
		responseTimeMs: 311,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message: "Backlog tăng mạnh ở invite-email-worker.",
		region: "queue-main",
	},
	{
		id: "svc_5",
		name: "Mail Service",
		category: "MAIL",
		status: "DOWN",
		uptimePercent: 96.72,
		responseTimeMs: 0,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message:
			"SMTP provider timeout liên tục, email support và invite đang fail.",
		region: "mail-provider-01",
	},
	{
		id: "svc_6",
		name: "Webhook Dispatcher",
		category: "WEBHOOK",
		status: "DEGRADED",
		uptimePercent: 98.93,
		responseTimeMs: 274,
		lastChecked: "2026-04-19T13:20:00.000Z",
		message: "Tỷ lệ retry Stripe / Slack webhook tăng bất thường.",
		region: "webhook-node-a",
	},
];

export const adminMonitoringEvents: MonitoringEvent[] = [
	{
		id: "evt_1",
		type: "QUEUE_FAILED",
		severity: "CRITICAL",
		status: "OPEN",
		title: "Queue backlog tăng mạnh ở invite-email-worker",
		serviceName: "Redis Queue",
		description:
			"Hàng đợi invite-email-worker tăng vượt ngưỡng 12.000 jobs trong 8 phút gần nhất.",
		createdAt: "2026-04-19T13:10:00.000Z",
		actor: "monitoring-bot",
		metadata: {
			queue: "invite-email-worker",
			backlog: 12384,
			failedJobsLast15m: 18,
			node: "worker-03",
		},
		resolutionNote: null,
	},
	{
		id: "evt_2",
		type: "EMAIL_FAILED",
		severity: "CRITICAL",
		status: "OPEN",
		title: "Email invite member thất bại hàng loạt",
		serviceName: "Mail Service",
		description:
			"Tỷ lệ gửi email thất bại vượt 40% trong 10 phút gần đây. Support và invite member bị ảnh hưởng.",
		createdAt: "2026-04-19T12:58:00.000Z",
		actor: "mail-monitor",
		metadata: {
			failedEmails: 34,
			provider: "smtp-relay-01",
			error: "Connection timeout",
			affectedFlows: ["workspace_invite", "support_reply"],
		},
		resolutionNote: null,
	},
	{
		id: "evt_3",
		type: "WEBHOOK_FAILED",
		severity: "WARNING",
		status: "ACKNOWLEDGED",
		title: "Stripe webhook retry vượt ngưỡng",
		serviceName: "Webhook Dispatcher",
		description:
			"Các webhook stripe.invoice.paid bị retry nhiều lần do timeout ở downstream billing service.",
		createdAt: "2026-04-19T12:32:00.000Z",
		actor: "webhook-monitor",
		metadata: {
			webhookProvider: "Stripe",
			failedWebhooks: 12,
			eventName: "invoice.paid",
			retryWindowMinutes: 20,
		},
		resolutionNote: "Đã xác nhận và đang theo dõi thêm.",
	},
	{
		id: "evt_4",
		type: "REQUEST_ERROR",
		severity: "CRITICAL",
		status: "OPEN",
		title: "API 5xx spike ở endpoint invite member",
		serviceName: "API Gateway",
		description:
			"Endpoint /workspaces/:id/invite tăng lỗi 502 và 504, trùng thời điểm mail service gặp sự cố.",
		createdAt: "2026-04-19T12:18:00.000Z",
		actor: "apm-agent",
		metadata: {
			endpoint: "/workspaces/:id/invite",
			errorRatePercent: 18.2,
			statusCodes: [502, 504],
			requestsPerMinute: 241,
		},
		resolutionNote: null,
	},
	{
		id: "evt_5",
		type: "ALERT",
		severity: "CRITICAL",
		status: "OPEN",
		title: "Mail Service đang DOWN",
		serviceName: "Mail Service",
		description:
			"Health check thất bại liên tục trong 5 chu kỳ. Toàn bộ luồng gửi mail phụ thuộc service này đang bị gián đoạn.",
		createdAt: "2026-04-19T12:05:00.000Z",
		actor: "health-checker",
		metadata: {
			service: "Mail Service",
			failedHealthChecks: 5,
			lastError: "SMTP socket timeout",
		},
		resolutionNote: null,
	},
	{
		id: "evt_6",
		type: "SYSTEM_LOG",
		severity: "INFO",
		status: "RESOLVED",
		title: "Cleanup job hoàn tất",
		serviceName: "Core API",
		description:
			"Cleanup job dọn subscription cũ và log rotate đã chạy xong mà không phát hiện lỗi.",
		createdAt: "2026-04-19T10:05:00.000Z",
		actor: "cron-runner",
		metadata: {
			job: "daily-cleanup",
			durationSeconds: 84,
			result: "success",
		},
		resolutionNote: "Không cần xử lý thêm.",
	},
	{
		id: "evt_7",
		type: "REQUEST_ERROR",
		severity: "WARNING",
		status: "RESOLVED",
		title: "Tăng lỗi OAuth callback tạm thời",
		serviceName: "Core API",
		description:
			"Lỗi redirect URI mismatch xuất hiện ngắn hạn sau khi rollout cấu hình OAuth mới.",
		createdAt: "2026-04-18T16:20:00.000Z",
		actor: "apm-agent",
		metadata: {
			flow: "google_oauth",
			errorRatePercent: 6.4,
			rolledBack: true,
		},
		resolutionNote: "Đã rollback cấu hình OAuth và xác nhận ổn định.",
	},
	{
		id: "evt_8",
		type: "WEBHOOK_FAILED",
		severity: "WARNING",
		status: "OPEN",
		title: "Slack webhook gửi alert thất bại",
		serviceName: "Webhook Dispatcher",
		description:
			"Một phần alert Slack không gửi được do giới hạn rate limit từ phía webhook endpoint.",
		createdAt: "2026-04-18T15:42:00.000Z",
		actor: "webhook-monitor",
		metadata: {
			webhookProvider: "Slack",
			failedEvents: 9,
			error: "429 rate_limited",
		},
		resolutionNote: null,
	},
];
