import type { AdminWorkspace } from "./workspace-admin.types";

export const adminWorkspaces: AdminWorkspace[] = [
	{
		id: "ws_1",
		name: "Acme Inc.",
		slug: "acme-inc",
		ownerId: "u_1",
		ownerName: "Nguyen Anh Nam",
		ownerEmail: "nam@example.com",
		status: "ACTIVE",
		plan: "ENTERPRISE",
		membersCount: 48,
		projectsCount: 12,
		boardsCount: 26,
		tasksCount: 1824,
		storageUsedGb: 18.4,
		storageLimitGb: 100,
		createdAt: "2026-02-12T09:00:00.000Z",
		lastActive: "2026-04-19T08:20:00.000Z",
		members: [
			{
				id: "u_1",
				name: "Nguyen Anh Nam",
				email: "nam@example.com",
				role: "OWNER",
			},
			{
				id: "u_2",
				name: "Tran Minh Khoa",
				email: "khoa@example.com",
				role: "ADMIN",
			},
			{
				id: "u_3",
				name: "Le Thi Huong",
				email: "huong@example.com",
				role: "MEMBER",
			},
		],
		activities: [
			{
				id: "a_1",
				action: "Nâng gói lên Enterprise",
				time: "2026-04-18T08:30:00.000Z",
			},
			{
				id: "a_2",
				action: "Tạo project Q2 Roadmap",
				time: "2026-04-17T14:00:00.000Z",
			},
			{
				id: "a_3",
				action: "Mời thêm 5 thành viên",
				time: "2026-04-16T09:30:00.000Z",
			},
		],
	},
	{
		id: "ws_2",
		name: "Nova Team",
		slug: "nova-team",
		ownerId: "u_4",
		ownerName: "Pham Gia Bao",
		ownerEmail: "bao@example.com",
		status: "ACTIVE",
		plan: "PRO",
		membersCount: 16,
		projectsCount: 6,
		boardsCount: 11,
		tasksCount: 542,
		storageUsedGb: 4.8,
		storageLimitGb: 25,
		createdAt: "2026-03-04T10:15:00.000Z",
		lastActive: "2026-04-18T16:40:00.000Z",
		members: [
			{
				id: "u_4",
				name: "Pham Gia Bao",
				email: "bao@example.com",
				role: "OWNER",
			},
			{
				id: "u_5",
				name: "Vo Thanh Dat",
				email: "dat@example.com",
				role: "ADMIN",
			},
			{
				id: "u_6",
				name: "Bui Hoang Yen",
				email: "yen@example.com",
				role: "MEMBER",
			},
		],
		activities: [
			{
				id: "a_4",
				action: "Tạo board Sprint Planning",
				time: "2026-04-18T10:20:00.000Z",
			},
			{
				id: "a_5",
				action: "Nâng gói lên Pro",
				time: "2026-04-12T07:00:00.000Z",
			},
		],
	},
	{
		id: "ws_3",
		name: "Pixel Studio",
		slug: "pixel-studio",
		ownerId: "u_7",
		ownerName: "Jessica Lee",
		ownerEmail: "jessica@example.com",
		status: "LOCKED",
		plan: "PRO",
		membersCount: 23,
		projectsCount: 8,
		boardsCount: 14,
		tasksCount: 760,
		storageUsedGb: 9.2,
		storageLimitGb: 25,
		createdAt: "2026-01-20T07:30:00.000Z",
		lastActive: "2026-04-14T18:00:00.000Z",
		members: [
			{
				id: "u_7",
				name: "Jessica Lee",
				email: "jessica@example.com",
				role: "OWNER",
			},
			{
				id: "u_8",
				name: "David Brown",
				email: "david@example.com",
				role: "ADMIN",
			},
			{
				id: "u_9",
				name: "Emily Tran",
				email: "emily@example.com",
				role: "MEMBER",
			},
		],
		activities: [
			{
				id: "a_6",
				action: "Workspace bị khóa bởi super admin",
				time: "2026-04-15T09:00:00.000Z",
			},
			{
				id: "a_7",
				action: "Phát hiện hoạt động bất thường",
				time: "2026-04-15T08:45:00.000Z",
			},
		],
	},
	{
		id: "ws_4",
		name: "Moon Labs",
		slug: "moon-labs",
		ownerId: "u_10",
		ownerName: "John Smith",
		ownerEmail: "john@example.com",
		status: "DELETED",
		plan: "FREE",
		membersCount: 8,
		projectsCount: 3,
		boardsCount: 5,
		tasksCount: 118,
		storageUsedGb: 1.6,
		storageLimitGb: 5,
		createdAt: "2026-02-28T12:00:00.000Z",
		lastActive: "2026-04-10T13:00:00.000Z",
		members: [
			{
				id: "u_10",
				name: "John Smith",
				email: "john@example.com",
				role: "OWNER",
			},
			{
				id: "u_11",
				name: "Anna Vo",
				email: "anna@example.com",
				role: "ADMIN",
			},
			{
				id: "u_12",
				name: "Minh Nguyen",
				email: "minh@example.com",
				role: "MEMBER",
			},
		],
		activities: [
			{
				id: "a_8",
				action: "Workspace bị xóa mềm",
				time: "2026-04-11T10:00:00.000Z",
			},
			{
				id: "a_9",
				action: "Giảm gói về Free",
				time: "2026-04-08T11:15:00.000Z",
			},
		],
	},
	{
		id: "ws_5",
		name: "Task Core",
		slug: "task-core",
		ownerId: "u_13",
		ownerName: "David Brown",
		ownerEmail: "david.brown@example.com",
		status: "ACTIVE",
		plan: "FREE",
		membersCount: 12,
		projectsCount: 5,
		boardsCount: 9,
		tasksCount: 308,
		storageUsedGb: 2.3,
		storageLimitGb: 5,
		createdAt: "2026-03-18T09:45:00.000Z",
		lastActive: "2026-04-19T06:15:00.000Z",
		members: [
			{
				id: "u_13",
				name: "David Brown",
				email: "david.brown@example.com",
				role: "OWNER",
			},
			{
				id: "u_14",
				name: "Emily Tran",
				email: "emily@example.com",
				role: "ADMIN",
			},
			{
				id: "u_15",
				name: "Bao Tran",
				email: "bao.tran@example.com",
				role: "MEMBER",
			},
		],
		activities: [
			{
				id: "a_10",
				action: "Tạo 24 task mới",
				time: "2026-04-19T05:40:00.000Z",
			},
			{
				id: "a_11",
				action: "Thêm board Bug Tracking",
				time: "2026-04-17T15:30:00.000Z",
			},
		],
	},
	{
		id: "ws_6",
		name: "Growth Lab",
		slug: "growth-lab",
		ownerId: "u_16",
		ownerName: "Olivia Nguyen",
		ownerEmail: "olivia@example.com",
		status: "ACTIVE",
		plan: "ENTERPRISE",
		membersCount: 31,
		projectsCount: 15,
		boardsCount: 29,
		tasksCount: 2140,
		storageUsedGb: 26.5,
		storageLimitGb: 100,
		createdAt: "2025-12-10T08:00:00.000Z",
		lastActive: "2026-04-18T20:10:00.000Z",
		members: [
			{
				id: "u_16",
				name: "Olivia Nguyen",
				email: "olivia@example.com",
				role: "OWNER",
			},
			{
				id: "u_17",
				name: "Kai Sou",
				email: "kai@example.com",
				role: "ADMIN",
			},
			{
				id: "u_18",
				name: "Nass",
				email: "nass@example.com",
				role: "ADMIN",
			},
		],
		activities: [
			{
				id: "a_12",
				action: "Tạo project Marketing Launch",
				time: "2026-04-18T18:20:00.000Z",
			},
			{
				id: "a_13",
				action: "Tăng storage sử dụng lên 26.5GB",
				time: "2026-04-17T19:10:00.000Z",
			},
		],
	},
];
